// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjrfxckburnzextoyske.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qcmZ4Y2tidXJuemV4dG95c2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDg0OTUsImV4cCI6MjA2NTIyNDQ5NX0.YaRBYUVyx0l5UIbWFNcSExTvc-NLwr7Em926VKMBgUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);